oro_menu_config:
    items:
        channels_submenu:
            label: 'Channels'
            uri: '#'
            extras:
                position: 50
        channels_list:
            label: 'Configuration'
            route: 'oro_integration_channel_index'
            extras:
                routes: 'oro_integration_channel_*'

    tree:
        application_menu:
            children:
                channels_submenu:
                    children:
                        channels_list: ~

oro_titles:
    oro_integration_channel_index:  ~
    oro_integration_channel_update: %%channel.name%%
    oro_integration_channel_create: Create Channel
