oro_menu_config:
    items:
        channels_submenu:
            label: 'oro.integration.menu.channels_submenu.label'
            uri: '#'
            extras:
                position: 50
        channels_list:
            label: 'oro.integration.menu.channels_list.label'
            route: oro_integration_channel_index
            extras:
                position: 10
                routes:  'oro_integration_channel_*'

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        channels_submenu:
                            children:
                                channels_list: ~

oro_titles:
    oro_integration_channel_index:  ~
    oro_integration_channel_update: '%%channel.name%%'
    oro_integration_channel_create: 'Create Channel'
