oro_menu_config:
    items:
        channels_submenu:
            label: 'Channels'
            uri: '#'
            extras:
                position: 50
        channels_list:
            label: 'Configuration'
            route: 'oro_integration_channel_index'

    tree:
        application_menu:
            children:
                channels_submenu:
                    children:
                        channels_list: ~

