oro_menu_config:
    items:
        customers_tab:
            label: 'Customers'
            uri: '#'
            extras:
                position: 10
        channels_submenu:
            label: 'Channels'
            uri: '#'
            extras:
                position: 50

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        channels_submenu: ~
