parameters:
    oro_integration.transport.rest.guzzle.client_factory.class: Oro\Bundle\IntegrationBundle\Provider\Rest\Client\Guzzle\GuzzleRestClientFactory
    oro_integration.transport.abstract.class:                   Oro\Bundle\IntegrationBundle\Provider\Rest\Transport\AbstractRestTransport

services:
    oro_integration.transport.rest.guzzle.client_factory:
        class: %oro_integration.transport.rest.guzzle.client_factory.class%

    oro_integration.transport.rest.client_factory:
        alias: oro_integration.transport.rest.guzzle.client_factory

    oro_integration.transport.rest.abstract:
        class: %oro_integration.transport.abstract.class%
        abstract: true
        calls:
            - [setRestClientFactory, [@oro_integration.transport.rest.client_factory]]
