Oro\Bundle\IntegrationBundle\Entity\Channel:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: { groups: [ Submit ] }
            - Length:
                min: 3
                max: 255
                groups: [ Submit ]
        type:
            - NotBlank: ~
