Oro\Bundle\IntegrationBundle\Entity\Channel:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        type:
            - NotBlank: ~

OroCRM\Bundle\MagentoBundle\Entity\MagentoSoapTransport:
    properties:
        wsdlUrl:
          - NotBlank: ~
        apiUser:
          - NotBlank: ~
        apiKey:
          - NotBlank: ~
