oro_integration_bundle:
    resource:     "@OroIntegrationBundle/Controller"
    type:         annotation
    prefix:       /

oro_integration_bundle_channel_api:
    resource: "@OroIntegrationBundle/Controller/Api/Rest/ChannelController.php"
    type:     rest
    prefix:   api/rest/{version}/
    defaults:
        version: latest
